folders:
  # Location: The location of the folder you want to scan - remember to remove the # before it for the option to work

  # ----- THE FOLLOWING OPTIONS CAN EITHER BE USED ALONE OR TOGETHER WITH THE OTHERS IN THIS SECTION ----- #
  #
  #   Age: Any files in the folder that are older than the specified amount of days will be deleted
  #   Count: If the folder has more than this many files, it will delete any extras starting from the oldest
  #   Size: Any files in the folder that are larger than the specified amount in kilobytes will be deleted
  #
  # ------------------------------------------------------------------------------------------------------ #

  # Set "age", "count", or "size" to -1 to disable that check

  # Important: Remember to change any '\' to '/' or there will be errors
  # Note: The plugin developer is not responsible for any accidentally deleted files - take backups regularly

  # You can add as many folders as you'd like
  1: # <- This can be whatever you want, just make sure it's unique
    #location: "/home/container/logs"
    age: 30
    count: 45
    size: 100
  2:
    #location: "/home/container/plugins/Skript/backups"
    age: -1
    count: 15
    size: -1
  3:
    #location: "/home/container/plugins/mcMMO/backup"
    age: 60
    count: -1
    size: -1
