main: net.silverstonemc.filecleanerspigot.FCSpigot
name: FileCleaner
description: Clean your old files!
version: s%VERSION%
author: JasonHorkles
website: https://github.com/SilverstoneMC/FileCleaner
api-version: 1.13
folia-supported: true

commands:
  filecleaner:
    description: "Base command for the FileCleaner plugin"
    usage: "§cUsage: /filecleaner <reload | cleannow>"
    aliases:
      - fc
    permission: filecleaner.command

permissions:
  filecleaner.command:
    default: op
    description: Permisison to see the base command
  filecleaner.reload:
    default: op
    description: Reload the plugin
  filecleaner.cleannow:
    default: op
    description: Force the files to be scanned and cleaned up now
  filecleaner.updatenotifs:
    default: op
    description: Notifications when there is an update available